# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSimple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='', max_length=50)),
                ('float_1', models.FloatField(default=0.0)),
                ('float_2', models.FloatField(default=0.0)),
                ('float_3', models.FloatField(default=0.0)),
                ('float_4', models.FloatField(default=0.0)),
                ('float_5', models.FloatField(default=0.0)),
                ('float_6', models.FloatField(default=0.0)),
                ('float_7', models.FloatField(default=0.0)),
                ('float_8', models.FloatField(default=0.0)),
                ('float_9', models.FloatField(default=0.0)),
            ],
        ),
    ]
