# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0002_remove_examplesimple_float_9'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplesimple',
            name='float_8',
        ),
    ]
