# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0004_notasperiodico'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasPorEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='', max_length=10)),
                ('year', models.CharField(default='', max_length=10, verbose_name='A\xf1o')),
                ('sucesos', models.IntegerField(default=0)),
            ],
        ),
    ]
